// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {textraapi} from '../models';

export function EnglishJapaneseFormat(arg1:string):Promise<string>;

export function Format(arg1:string):Promise<string>;

export function GenerateHtml(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadApiKey():Promise<textraapi.ApiKey>;

export function Translate(arg1:string):Promise<string>;

export function TranslateFormat(arg1:string):Promise<string>;

export function WriteApiKey(arg1:textraapi.ApiKey):Promise<void>;
