// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnglishJapaneseFormat(arg1) {
  return window['go']['main']['App']['EnglishJapaneseFormat'](arg1);
}

export function Format(arg1) {
  return window['go']['main']['App']['Format'](arg1);
}

export function GenerateHtml(arg1) {
  return window['go']['main']['App']['GenerateHtml'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadApiKey() {
  return window['go']['main']['App']['ReadApiKey']();
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}

export function TranslateFormat(arg1) {
  return window['go']['main']['App']['TranslateFormat'](arg1);
}

export function WriteApiKey(arg1) {
  return window['go']['main']['App']['WriteApiKey'](arg1);
}
