// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchArrangeSentences(arg1) {
  return window['go']['main']['App']['FetchArrangeSentences'](arg1);
}

export function FetchTranslation(arg1) {
  return window['go']['main']['App']['FetchTranslation'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
